name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip
          pip install --upgrade setuptools wheel # Upgrade setup tools
          pip install --no-cache-dir -r requirements.txt pytest pytest-cov  # Install dependencies

      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}" >> $GITHUB_ENV

      - name: Install package in editable mode
        run: pip install -e .
      
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          pytest tests/