name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip
          pip install --upgrade setuptools wheel # Upgrade setup tools
          pip install --no-cache-dir -r requirements.txt pytest pytest-cov  # Install dependencies

      - name: Run tests with coverage report
        run: |
          pytest --cov=src --cov-report term-missing tests/unit  # Corrected test path based on project structure
